### ISSUE TITLE
showImage should be a configurable setting

### ISSUE THREAD

**Issue by Blackbaud-KevinEnns** [blackbaud/skyux-errors#17]
### Expected behavior
I can specify an `errorType` and `showImage=false` and get the default text with no image

### Actual behavior
if `errorType` is set, the image is always shown

### Steps to reproduce
add a `<skyux-error>` with a specified `errorType` like `errorType="broken"` and note that you cannot specify whether or not the image is shown

### Severity
low

### Impact
The workaround is to make a custom title and custom description and just copy the text from the default.  This is bad, though, because if the default text changes, it would not automatically update where this workaround is implemented.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.0`
