### ISSUE TITLE
Deprecate SkyErrorModalService

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux-errors#38]
Based on previous [convo](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1600277812225300?thread_ts=1600270876.217500&cid=C3TQ4C0KG), the `SkyErrorModalService` isn't intended to be used. Thus it makes sense to deprecate it, remove it from the docs, and remove it from the next major release.

**Comment by Blackbaud-SteveBrush** [comment]
We talked more about this and decided that there is a use-case for error modals, as described here: https://github.com/blackbaud/skyux-errors/issues/41
