### ISSUE TITLE
Update developer guidelines for `SkyErrorModalService` for appropriate usage

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-errors#41]
On the Developer tab, within the `SkyErrorModalService` description, we need to explain the use case for using an error modal:
- If a specific action would normally launch a modal, but a call to a remote server results in an error, the error modal should be shown.

[AB#1581077](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1581077)

**Comment by Blackbaud-ColbyWhite** [comment]
for clarity, Is this use case
- If a specific action would normally launch a modal, but in loading said modal a call to a remote server results in an error, the first modal should be closed and replaced with the error modal.
or is it
- If a specific action would normally launch a modal, but _before_ loading said modal a call to a remote server results in an error, the error modal should be show.

to word another way, is the idea: if an error happens _before_ showing the regular modal, handle the error with an error modal. if an error happens _after_ showing a regular modal, handle the error with an error component _inside_ said regular modal.

i can see the case where a dev as the option for each; which should they choose? for example, if a button is supposed to open a modal that contains info regarding payment configurations, should the call to get the payment config info be before or after the modal? 

button click -> getPaymentConfig -> show appropriate modal based on success/error

or

button click -> show modal with loading icon -> getPaymentConfig -> show regular modal with content based on success/error

there's probably scenarios where you _have_ to do one or the other, but i would imagine most scenarios could be accomplished either way. curious which is preferred?

**Comment by Blackbaud-SteveBrush** [comment]
Your second bullet is the behavior we'd use the error modal for, yes.

**Comment by Blackbaud-ColbyWhite** [comment]
makes sense, but this part of the question remains unanswered.

> i can see the case where a dev as the option for each; which should they choose?

to the user, i think both scenarios look the same. thus if some are choosing one route and other are choosing the other, something that looks the same to the user can result in two different types of error modals

**Comment by Blackbaud-SteveBrush** [comment]
The flow would look like:
1. User click button to start some async process. Launch a page-blocking wait to prevent user interaction.
2. If the async task results in a failure, display the error modal.
3. If the async task results in success, display the intended modal.
